import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-950">
        <header className="flex justify-around py-6 text-xl">
          <strong className="text-white">Logo</strong>
          <ul className="flex gap-4">
            <li>
              <Link
                className="text-white hover:text-gray-300 transition duration-300"
                href="/"
              >
                Home
              </Link>
            </li>
            <li>
              <Link
                className="text-white hover:text-gray-300 transition duration-300"
                href="/dashboard"
              >
                Dashboard
              </Link>
            </li>
            <li>
              <Link
                className="text-white hover:text-gray-300 transition duration-300"
                href="/region"
              >
                Region
              </Link>
            </li>
          </ul>
        </header>
        {children}
      </body>
    </html>
  );
}
